### ISSUE TITLE
Add support for profiling benchmarks

### ISSUE THREAD

**Issue by bheisler** [ferrous-systems/flamegraph#1]
This looks like a useful project! I've had a few folks ask for profiling support to be added to Criterion.rs; now I can direct them to cargo-flamegraph.

That being the case, it seems like it would be useful to have the ability to run `cargo bench` inside a profiler with cargo-flamegraph. Is that supported? I didn't see it in the documentation. Naturally, it should be possible to pass arguments to the benchmark executables as well, probably using the same `--` separator that Cargo itself uses.

**Comment by BourgondAries** [comment]
This would be extremely useful
