### ISSUE TITLE
Panics on OSX: unable to generate a flame graph

### ISSUE THREAD

**Issue by velvia** [ferrous-systems/flamegraph#16]
First of all, thanks so much for adding support to dtrace and OSX!

I'm trying to use cargo flame graph on bench output on OSX.  This is how I run it:

`sudo cargo flamegraph --exec="target/release/bench-aba573ea464f3f67"`

(where bench-aba... is the executable produced by running cargo bench first)

The error:

```
unpack delta u64s       time:   [73.363 ns 73.823 ns 74.303 ns]
                        change: [-22.503% -20.920% -19.423%] (p = 0.00 < 0.05)
                        Performance has improved.

dtrace: pid 87448 has exited
thread 'main' panicked at 'unable to generate a flamegraph from the collapsed stack data: Io(Custom { kind: InvalidData, error: StringError("No stack counts found") })', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

NOTE:  this is how I used to run dtrace to get a flame graph:

```
sudo dtrace -c './target/release/bench-2022f41cf9c87baf --profile-time 120' -o out.stacks -n 'profile-997 /pid == $target/ { @[ustack(100)] = count(); }'
~/src/github/FlameGraph/stackcollapse.pl out.stacks | ~/src/github/FlameGraph/flamegraph.pl >rust-bench.svg
```

I did not add --profile-time this time but I don't think that would make a difference.

**Comment by spacejam** [comment]
Hey @velvia, does this error still happen with the new standalone `flamegraph` binary instead of passing `--exec...` to `cargo-flamegraph`?

What operating system version are you using?

Is the cargo-flamegraph.stacks file totally empty? If not, could you please paste it here?

**Comment by velvia** [comment]
@spacejam 10.13.6, and there's no cargo-flamegraph.stacks file... unless it outputs in a different dir.

Sorry what do you mean by "standalone flame graph binary"?

**Comment by Feliix42** [comment]
I _had_ this issue as well, but after updating to the latest (v0.1.12) version of flamegraph this worked fine for me.

@velvia The newer releases additionally install a binary called `flamegraph`.

**Comment by velvia** [comment]
Yeah, seems the latest version is working now.   I can run `sudo flamegraph bench-.....` etc. and it generates a flamegraph.

I do see errors like this, but I think can close it.
```
dtrace: error on enabled probe ID 1 (ID 34: profile:::profile-997): invalid address (0x63f9762928206260) in action #2
dtrace: error on enabled probe ID 1 (ID 34: profile:::profile-997): invalid address (0x2545a7a2) in action #2
dtrace: error on enabled probe ID 1 (ID 34: profile:::profile-997): invalid address (0x2545a7a2) in action #2
```

**Comment by keroro520** [comment]
Same error still exists with v0.1.13, and OSX version is Mojave 10.14.
After reporting below errors, target executable ends but not flamegraph generated.
Can I reopen this PR ?

```
...
dtrace: error on enabled probe ID 1 (ID 34: profile:::profile-997): invalid address (0x762e73ea) in action #2
dtrace: error on enabled probe ID 1 (ID 34: profile:::profile-997): invalid address (0x33f087b3) in action #2
dtrace: error on enabled probe ID 1 (ID 34: profile:::profile-997): invalid address (0xfffffffe) in action #2
dtrace: error on enabled probe ID 1 (ID 34: profile:::profile-997): invalid address (0xfffffeff) in action #2
thread 'main' panicked at 'unable to collapse generated profile data: Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by zeeshanlakhani** [comment]
Howdy. 

I'm receiving this error error within a container running on MacOS Mojave (via multiple runs on 0.1.13 and the current git/master version):

```shell
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.119 MB perf.data (8 samples) ]
writing flamegraph to "flamegraph.svg"
thread 'main' panicked at 'unable to generate a flamegraph from the collapsed stack data: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/libcore/result.rs:1165:5
```

Can we reopen this or am I doing something awry? Thanks.
