### ISSUE TITLE
Passing perf record -F option

### ISSUE THREAD

**Issue by Shadlock0133** [ferrous-systems/flamegraph#21]
perf record can take -F option to control sampling frequency. Adding a way to pass it to perf would be useful.

**Comment by ambiso** [comment]
I would certainly be interested in this feature as well!

The currently set sampling rate is 99 Hz. I found the culprit [>here<](https://github.com/ferrous-systems/flamegraph/blob/49b1ad87cfaab97fe39e6ba5b3fb199241cd74c7/src/lib.rs#L44).

I don't know about non-linux system, however [>here's<](https://github.com/ferrous-systems/flamegraph/blob/e83bcc9cad40df0c22979cc52145d77f878880f2/src/lib.rs#L81) the profiling command.

One could insert the option into the [structopt](https://github.com/ferrous-systems/flamegraph/blob/a802af1baddeda9d5c3c6203c0d1785bd81beb24/src/main.rs#L31).

**Comment by Shadlock0133** [comment]
If I'm not mistaken, main.rs isn't really used here any more so changes would be in bin folder.

I was wondering whether new Opt struct member should be `Option<String>` or `Option<CustomEnum>`.
There is also problem how to pass is to the args string.

I already started implementing it on local branch.

**Comment by marcusklaas** [comment]
@Shadlock0133 any progress on this? I'm also mega interested in this feature.

**Comment by Shadlock0133** [comment]
I pushed it here https://github.com/Shadlock0133/flamegraph/tree/freq. Practically untested. Reviews and comments are welcome.

**Comment by marcusklaas** [comment]
Looks good to me! Have you considered making a pull request to merge it upstream?

**Comment by Shadlock0133** [comment]
If somebody can tests that it works on Mac, sure.

**Comment by ambiso** [comment]
I've added a comment for review :blush:

**Comment by Shadlock0133** [comment]
Pushed the fix

**Comment by jamestwebber** [comment]
👍 from me for this option, I'm trying to profile a rather long-running program and the `perf.data` file is getting huge...
