### ISSUE TITLE
windows install error

### ISSUE THREAD

**Issue by zydxhs** [ferrous-systems/flamegraph#49]
OS: win10
Rust: 1.38 stable amd64
cargo install flamegraph, I get error like this:

   Compiling inferno v0.4.1
   Compiling cargo_metadata v0.7.4
   Compiling flamegraph v0.1.13
error[E0425]: cannot find value `exit_status` in this scope
   --> d:\Program\cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\flamegraph-0.1.13\src\lib.rs:134:6
    |
134 |     !exit_status.success()
    |      ^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `flamegraph`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `flamegraph v0.1.13`, intermediate artifacts can be found at `C:\Temp\cargo-installwtC1Id`

Caused by:
  build failed

**Comment by ConnorSkees** [comment]
I am also facing this issue on Windows 10.
Toolchain: `stable-x86_64-pc-windows-msvc`
Rustc: `rustc 1.39.0 (4560ea788 2019-11-04)`
```
error[E0425]: cannot find value `exit_status` in this scope
--> C:\.cargo\registry\src\github.com-1ecc6299db9ec823\flamegraph-0.1.13\src\lib.rs:134:6
    |
134 |    !exit_status.success()
    |     ^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: failed to compile `flamegraph v0.1.13`
```
I guess something went wrong when refactoring [here](https://github.com/ferrous-systems/flamegraph/commit/49b1ad87cfaab97fe39e6ba5b3fb199241cd74c7#diff-b4aea3e418ccdb71239b96952d9cddb6R132)

**Comment by zydxhs** [comment]
base v0.1.13, Just make the following changes and it will compile:

position: flamegraph-0.1.13\src\lib.rs:134:6
!exit_status.success() -> !status.success()

**Comment by ConnorSkees** [comment]
@zydxhs I additionally had trouble building because of `signal_hook`, do you not run into this when building?

**Comment by zydxhs** [comment]
@ConnorSkees Don not use the master version, there are many compilation errors.

**Comment by jonas-schievink** [comment]
This is now fixed on master.
